# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/zybo_rocketchip_ZynqMediumFPGAConfig/zybo_rocketchip_ZynqMediumFPGAConfig.cache/wt [current_project]
set_property parent.project_path /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/zybo_rocketchip_ZynqMediumFPGAConfig/zybo_rocketchip_ZynqMediumFPGAConfig.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/src/verilog/clocking.vh
add_files /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/zybo_rocketchip_ZynqMediumFPGAConfig/zybo_rocketchip_ZynqMediumFPGAConfig.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/zybo_rocketchip_ZynqMediumFPGAConfig/zybo_rocketchip_ZynqMediumFPGAConfig.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/zybo_rocketchip_ZynqMediumFPGAConfig/zybo_rocketchip_ZynqMediumFPGAConfig.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/zybo_rocketchip_ZynqMediumFPGAConfig/zybo_rocketchip_ZynqMediumFPGAConfig.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/zybo_rocketchip_ZynqMediumFPGAConfig/zybo_rocketchip_ZynqMediumFPGAConfig.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/zybo_rocketchip_ZynqMediumFPGAConfig/zybo_rocketchip_ZynqMediumFPGAConfig.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/zybo_rocketchip_ZynqMediumFPGAConfig/zybo_rocketchip_ZynqMediumFPGAConfig.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/zybo_rocketchip_ZynqMediumFPGAConfig/zybo_rocketchip_ZynqMediumFPGAConfig.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/zybo_rocketchip_ZynqMediumFPGAConfig/zybo_rocketchip_ZynqMediumFPGAConfig.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib {
  /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/src/verilog/AsyncResetReg.v
  /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/src/verilog/plusarg_reader.v
  /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/src/verilog/Top.ZynqMediumFPGAConfig.v
  /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/src/verilog/rocketchip_wrapper.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/src/constrs/base.xdc
set_property used_in_implementation false [get_files /home/dylan/MEGA/Documents/School/2020-21/ECE/530/RISC-Y-Zybo/fpga-zynq/zybo/src/constrs/base.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top rocketchip_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef rocketchip_wrapper.dcp

catch { report_utilization -file rocketchip_wrapper_utilization_synth.rpt -pb rocketchip_wrapper_utilization_synth.pb }
